services:
  postgres:
    image: 'postgres:15.1'
    env_file:
      - '/secrets/db.env'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  sw_api:
    build: '.'
    restart: always
    depends_on:
      - 'postgres'
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    env_file:
      - '/secrets/sw_api.env'
    command: bash -c "(rake db:migrate:status 2>/dev/null || rake db:setup) && rake db:migrate && rails s -b 0.0.0.0"

volumes:
  postgres: {}
